language: elixir
elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.4

jobs:
  include:
    - elixir: 1.10.4
      otp_release: 23.0

cache:
  directories:
    - _build
    - deps

branches:
  only:
  - master
  - develop
  - /^feature.*$/
  - /^release.*$/

script:
- make compile
- MIX_ENV=test mix coveralls.travis

notifications:
  email: false
