language: elixir
elixir:
  - 1.5.2
  - 1.7.4
  - 1.8
  - 1.9.2

cache:
  directories:
    - _build
    - deps

branches:
  only:
  - master
  - develop

script:
- make compile
- make test

notifications:
  email: false
