language: elixir
elixir:
  - 1.7.4
  - 1.8
  - 1.9.2

cache:
  directories:
    - _build
    - deps

branches:
  only:
  - master
  - develop
  - /^feature.*$/

script:
- make compile
- make test
- MIX_ENV=test mix coveralls.travis

notifications:
  email: false
